services:
  db:
    image: mysql:8.0.28
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Shanghai
    ports:
      - '3306:3306'
    volumes:
      - mysql-leaf:/var/lib/mysql
  redis:
    image: redis
    ports:
      - '6379:6379'
volumes:
  mysql-leaf:
